MVCProject/Controllers/AdminsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCProject.Models;
using MVCProject.ViewModel;
namespace MVCProject.Controllers
{
    public class AdminsController : Controller
    {
        private MyDataContext db = new MyDataContext();

        // GET: Admins
        public ActionResult Index()
        {
            return View(db.Admins.ToList());
        }

        // GET: Admins/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Admin admin = db.Admins.Find(id);
            if (admin == null)
            {
                return HttpNotFound();
            }
            return View(admin);
        }

        // GET: Admins/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admins/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Admin_Id,Password")] Admin admin)
        {
            if (ModelState.IsValid)
            {
                db.Admins.Add(admin);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(admin);
        }

        // GET: Admins/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Admin admin = db.Admins.Find(id);
            if (admin == null)
            {
                return HttpNotFound();
            }
            return View(admin);
        }

        // POST: Admins/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Admin_Id,Password")] Admin admin)
        {
            if (ModelState.IsValid)
            {
                db.Entry(admin).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(admin);
        }

        // GET: Admins/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Admin admin = db.Admins.Find(id);
            if (admin == null)
            {
                return HttpNotFound();
            }
            return View(admin);
        }

        // POST: Admins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Admin admin = db.Admins.Find(id);
            db.Admins.Remove(admin);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Admin_Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Admin_Login(Admin admin)
        {
            var email = admin.Email;
            var pass = admin.Password;
            //var data = db.Admins.Where(add => add.Password.Trim() == pass && add.Admin_Id == id).FirstOrDefault();
            var data = db.Admins.Where(add => add.Password == pass && add.Email.Trim()==email).FirstOrDefault();
            if (data != null && Session["myid"]==null)
            {  
                Session["myid"] = email;
                Session["username"] = "Admin";
                var Department = db.Departments.ToList();
                var viewModel = new NewFacultyViewModel()
                {
                    department = Department
                };
                return View("Admin_level1", viewModel);
            }
             return RedirectToAction("Admin_Login");
            //return RedirectToAction("Submit");
        }

        public JsonResult IsUserExists(string email)
        {
            //check if any of the UserName matches the UserName specified in the Parameter using the ANY extension method.  
            return Json(!db.Admins.Any(x => x.Email == email), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Submit(Faculty faculty)
        {
            if (Session["myid"] != null)
            {
                db.Faculties.Add(faculty);
                db.SaveChanges();
                var fact = db.Faculties.ToList();
                return View("Registration", fact);
            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult FacultyList(string searchstring,string sortorder)
        {
            if (Session["myid"] != null)
            {
                //ViewBag.DepartmentNameSortParam = string.IsNullOrEmpty(sortorder) ? "DName_Desc" : "";
                ViewBag.FacultyName = sortorder == "Name" ? "Name_Desc" : "Name";
                var list_faculty = from f in db.Faculties select f;
                if (!string.IsNullOrEmpty(searchstring))
                {
                    
                    list_faculty = list_faculty.Where(x => x.Name.Contains(searchstring));

                }
                switch (sortorder)
                {
                    case "Name_Desc":
                        list_faculty = list_faculty.OrderByDescending(x => x.Name);
                            break;
                    case "Name":
                        list_faculty = list_faculty.OrderBy(x => x.Name);
                        break;
                    default:
                        break;
                }
                return View(list_faculty);
            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Logout()
        {
            if (Session["myid"] != null)
            {
                Session.Abandon();
                return RedirectToAction("Index","Home");
            }
            return RedirectToAction("Index", "Home");

        }
    }
}

MVCProject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCProject.Models;
namespace MVCProject.Controllers
{
    public class HomeController : Controller
    {
        MyDataContext db = new MyDataContext();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Logout()
        {
            if (Session["myid"] != null)
            {
                Session.Abandon();
            }
            return RedirectToAction("Index", "Home");

        }

    }
}

MVCProject/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCProject.Models;

namespace MVCProject.Controllers
{
    public class StudentsController : Controller
    {
        private MyDataContext db = new MyDataContext();

        // GET: Students
        public ActionResult Index()
        {
            var students = db.Students.Include(s => s.dept);
            return View(students.ToList());
        }

        // GET: Students/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // GET: Students/Create
        public ActionResult Create()
        {
            ViewBag.Dept_Id = new SelectList(db.Departments, "Dept_Id", "Name");
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Stud_Id,Name,Password,Dept_Id,Attendance,TotalDays")] Student student)
        {
            if (ModelState.IsValid)
            {
                db.Students.Add(student);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Dept_Id = new SelectList(db.Departments, "Dept_Id", "Name", student.Dept_Id);
            return View(student);
        }

        // GET: Students/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            ViewBag.Dept_Id = new SelectList(db.Departments, "Dept_Id", "Name", student.Dept_Id);
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Stud_Id,Name,Password,Dept_Id,Attendance,TotalDays")] Student student)
        {
            if (ModelState.IsValid)
            {
                db.Entry(student).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Dept_Id = new SelectList(db.Departments, "Dept_Id", "Name", student.Dept_Id);
            return View(student);
        }

        // GET: Students/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Student student = db.Students.Find(id);
            db.Students.Remove(student);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(Student student)
        {

            var email = student.Email;
            var pass = student.Password;
            var data = db.Students.Where(add => add.Password.Trim() == pass && add.Email == email).FirstOrDefault();
            if (data != null && Session["myid"] == null)
            {
                Session["myid"] = email;
                Session["username"] = data.Name;
                return View("Student_Details",data);    
            }
            return RedirectToAction("Login");
        }

        public JsonResult IsUserExists(string email)
        {
            //check if any of the UserName matches the UserName specified in the Parameter using the ANY extension method.  
            return Json(!db.Students.Any(x => x.Email == email), JsonRequestBehavior.AllowGet);
        }

        public ActionResult Logout()
        {
            if (Session["myid"] != null)
            {
                Session.Abandon();
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Index","Home");

        }

    }
}

MVCProject/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>About Us</h2>
<h3>Meet the Developers of this Project- </h3>

<div class="row">
    <div class="col-sm-4 col-md-4">
        <div class="thumbnail">
            <img src="~/Content/Profile_maharshi.jpg" alt="maharshi" width="300px" height="300px">
            <div class="caption">
                <h3>Maharshi Dave </h3>
                <p>Developer</p>
             </div>
        </div>
    </div>
    <div class="col-sm-4 col-md-4">
        <div class="thumbnail">
            <img src="~/Content/jaimit.jpg" alt="jaimit" width="300px" height="300px">
            <div class="caption">
                <h3>Jaimit Gandhi</h3>
                <p>Developer</p>
               </div>
        </div>
    </div>
    <div class="col-sm-4 col-md-4">
        <div class="thumbnail">
            <img src="~/Content/ishan2.jpg" alt="ishan" width="300px" height="300px">
            <div class="caption">
                <h3>Ishan Ghelani</h3>
                <p>Developer</p>
            </div>
        </div>
    </div>

</div>

MVCProject/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>Contact Us</h2>
<h3>You can contact us through email or feel free to visit us at- </h3>

<address>
    Dharmsinh Desai University,<br />
    Nadiad.<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">contact@ams.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">marketing@ams.com</a><br><br>
    <strong>Developers Email-<strong><br>
    <a href="mailto:jaimitgandhi9@gmail.com">jaimitgandhi9@gmail.com</a><br />
    <a href="mailto:ishanghelani1@gmail.com">ishanghelani1@gmail.com</a><br />
    <a href="mailto:davemaharshi7@gmail.com">davemaharshi7@gmail.com</a><br />

</address>

MVCProject/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<div class="jumbotron">
    <h1>Student Portal</h1>
    <p class="lead">Welcomes you.</p>
    </div>

<div class="row">
    <div class="col-md-4">
        <h2>Are you Student?</h2>

        @using (Html.BeginForm("Login", "Students", FormMethod.Get, new { @class = "form-horizontal", role = "form" }))
        {
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="STUDENT" class="btn btn-primary" />
                </div>
            </div>
        }
    </div>
    <div class="col-md-4">
        <h2>For Faculties</h2>

        @using (Html.BeginForm("Login", "Faculties", FormMethod.Get, new { @class = "form-horizontal", role = "form" }))
        {
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="FACULTY" class="btn btn-info" />
                </div>
            </div>
        }

    </div>
    <div class="col-md-4">
        <h2>For Admin</h2>

        @using (Html.BeginForm("Admin_Login", "Admins", FormMethod.Get, new { @class = "form-horizontal", role = "form" }))
        {
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="ADMIN" class="btn btn-danger" />
                </div>
            </div>
        }

        </div>
</div>