MVCProject/Controllers/AdminsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCProject.Models;
using MVCProject.ViewModel;
namespace MVCProject.Controllers
{
    public class AdminsController : Controller
    {
        private MyDataContext db = new MyDataContext();

        // GET: Admins
        public ActionResult Index()
        {
            return View(db.Admins.ToList());
        }

        // GET: Admins/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Admin admin = db.Admins.Find(id);
            if (admin == null)
            {
                return HttpNotFound();
            }
            return View(admin);
        }

        // GET: Admins/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admins/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Admin_Id,Password")] Admin admin)
        {
            if (ModelState.IsValid)
            {
                db.Admins.Add(admin);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(admin);
        }

        // GET: Admins/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Admin admin = db.Admins.Find(id);
            if (admin == null)
            {
                return HttpNotFound();
            }
            return View(admin);
        }

        // POST: Admins/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Admin_Id,Password")] Admin admin)
        {
            if (ModelState.IsValid)
            {
                db.Entry(admin).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(admin);
        }

        // GET: Admins/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Admin admin = db.Admins.Find(id);
            if (admin == null)
            {
                return HttpNotFound();
            }
            return View(admin);
        }

        // POST: Admins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Admin admin = db.Admins.Find(id);
            db.Admins.Remove(admin);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Admin_Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Admin_Login(Admin admin)
        {
            var email = admin.Email;
            var pass = admin.Password;
            //var data = db.Admins.Where(add => add.Password.Trim() == pass && add.Admin_Id == id).FirstOrDefault();
            var data = db.Admins.Where(add => add.Password == pass && add.Email.Trim()==email).FirstOrDefault();
            if (data != null && Session["myid"]==null)
            {  
                Session["myid"] = email;
                Session["username"] = "Admin";
                var Department = db.Departments.ToList();
                var viewModel = new NewFacultyViewModel()
                {
                    department = Department
                };
                return View("Admin_level1", viewModel);
            }
             return RedirectToAction("Admin_Login");
            //return RedirectToAction("Submit");
        }

        public JsonResult IsUserExists(string email)
        {
            //check if any of the UserName matches the UserName specified in the Parameter using the ANY extension method.  
            return Json(!db.Admins.Any(x => x.Email == email), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Submit(Faculty faculty)
        {
            if (Session["myid"] != null)
            {
                db.Faculties.Add(faculty);
                db.SaveChanges();
                var fact = db.Faculties.ToList();
                return View("Registration", fact);
            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult FacultyList(string searchstring,string sortorder)
        {
            if (Session["myid"] != null)
            {
                //ViewBag.DepartmentNameSortParam = string.IsNullOrEmpty(sortorder) ? "DName_Desc" : "";
                ViewBag.FacultyName = sortorder == "Name" ? "Name_Desc" : "Name";
                var list_faculty = from f in db.Faculties select f;
                if (!string.IsNullOrEmpty(searchstring))
                {
                    
                    list_faculty = list_faculty.Where(x => x.Name.Contains(searchstring));

                }
                switch (sortorder)
                {
                    case "Name_Desc":
                        list_faculty = list_faculty.OrderByDescending(x => x.Name);
                            break;
                    case "Name":
                        list_faculty = list_faculty.OrderBy(x => x.Name);
                        break;
                    default:
                        break;
                }
                return View(list_faculty);
            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Logout()
        {
            if (Session["myid"] != null)
            {
                Session.Abandon();
                return RedirectToAction("Index","Home");
            }
            return RedirectToAction("Index", "Home");

        }
    }
}

MVCProject/Controllers/FacultiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCProject.Models;
using MVCProject.ViewModel;
using PagedList;
namespace MVCProject.Controllers
{
    public class FacultiesController : Controller
    {
        private MyDataContext db = new MyDataContext();

        // GET: Faculties
        public ActionResult Index()
        {
            var faculty = db.Faculties.Include(f => f.dept);
            return View(faculty.ToList());
        }

        // GET: Faculties/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Faculty faculty = db.Faculties.Find(id);
            if (faculty == null)
            {
                return HttpNotFound();
            }
            return View(faculty);
        }

        // GET: Faculties/Create
        public ActionResult Create()
        {
            ViewBag.Dept_Id = new SelectList(db.Departments, "Dept_Id", "Name");
            return View();
        }

        // POST: Faculties/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Fact_Id,Name,Password,Dept_Id")] Faculty faculty)
        {
            if (ModelState.IsValid)
            {
                db.Faculties.Add(faculty);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Dept_Id = new SelectList(db.Departments, "Dept_Id", "Name", faculty.Dept_Id);
            return View(faculty);
        }

        // GET: Faculties/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Faculty faculty = db.Faculties.Find(id);
            /*if (faculty == null)
            {
                return HttpNotFound();
            }
            ViewBag.Dept_Id = new SelectList(db.Departments, "Dept_Id", "Name", faculty.Dept_Id);
            return View(faculty);*/
            return RedirectToAction("Edit","Students",id);
        }

        // POST: Faculties/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Faculty faculty)
        {
            if (ModelState.IsValid)
            {
                db.Entry(faculty).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Dept_Id = new SelectList(db.Departments, "Dept_Id", "Name", faculty.Dept_Id);
            return View(faculty);
        }

        // GET: Faculties/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Faculty faculty = db.Faculties.Find(id);
            if (faculty == null)
            {
                return HttpNotFound();
            }
            return View(faculty);
        }

        // POST: Faculties/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Faculty faculty = db.Faculties.Find(id);
            db.Faculties.Remove(faculty);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(Faculty faculty)
        {

            var email = faculty.Email;
            var pass = faculty.Password;
            var data = db.Faculties.Where(add => add.Password.Trim() == pass && add.Email == email).FirstOrDefault();
            if (data != null && Session["myid"] == null)
            {
                Session["myid"] = email;
                Session["username"] = data.Name;
                var Department = db.Departments.ToList();
                var viewModel = new NewStudentViewModel()
                {
                    department = Department
                };

                Session["department_id"] = data.Dept_Id;
                return View("Faculty_level1", viewModel);
            }
             return RedirectToAction("Login");
        }

        public JsonResult IsUserExists(string email)
        {
            //check if any of the UserName matches the UserName specified in the Parameter using the ANY extension method.  
            return Json(!db.Faculties.Any(x => x.Email == email), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Submit(Student student)
        {
            if (Session["department_id"].ToString() != null && Session["myid"] != null)
            {
                student.Dept_Id = Int32.Parse(Session["department_id"].ToString());

                db.Students.Add(student);
                db.SaveChanges();
                // var stud = db.Students.ToList();
                //return View("Registration", stud);
                return View("StudentList");
            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult StudentList(string searchstring,string sortorder,int? page)
        {
            if (Session["myid"] != null)
            {
                ViewBag.StudentName = string.IsNullOrEmpty(sortorder) ? "Name_Desc" : "";
                ViewBag.StudentAttendance = sortorder == "Attendance" ? "Attendance_Desc" : "Attendance";
                int facultyid = Int32.Parse(Session["department_id"].ToString());
                var stud = db.Students.Where(std => std.Dept_Id == facultyid);
                if (!string.IsNullOrEmpty(searchstring))
                {

                    stud = stud.Where(x => x.Name.Contains(searchstring));

                }
                stud = stud.OrderBy(x => x.Stud_Id);
                int pagesize = 3;
                int pagenumber = (page ?? 1);
                switch (sortorder)
                {
                    case "Name_Desc":
                        stud = stud.OrderByDescending(x => x.Name);
                        break;
                    case "Attendance_Desc":
                        stud = stud.OrderByDescending(x => x.Attendance);
                        break;
                    case "Attendance":
                        stud = stud.OrderBy(x => x.Attendance);
                        break;
                    default:
                        break;
                }
                return View(stud.ToPagedList(pagenumber, pagesize));
            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Logout()
        {
            if (Session["myid"] != null)
            {
                Session.Abandon();
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Index", "Home");

        }
    }
}

MVCProject/Views/Admins/Admin_Login.cshtml
@model MVCProject.Models.Admin

@{
    ViewBag.Title = "Admin_Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Admin_Login</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm1">
            @using (Html.BeginForm("Admin_Login", "Admins", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <h4>Use a local account to log in.</h4>
                <hr />
                 @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>

                @* Enable this once you have account confirmation enabled for password reset functionality
                    <p>
                        @Html.ActionLink("Forgot your password?", "ForgotPassword")
                    </p>*@
            }
        </section>
    </div>

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCProject/Views/Admins/Admin_level1.cshtml
@model MVCProject.ViewModel.NewFacultyViewModel

@{
    ViewBag.Title = "Admin_level1";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Admin_level1</h2>

<div class="row">
    <div class="col-md-8">
        <section id="loginForm1">
            @using (Html.BeginForm("Submit", "Admins", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                @Html.ActionLink("List of Faculties","FacultyList")<br />
                <h4>Add new Faculty.</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(m => m.faculty.Name, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.faculty.Name, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.faculty.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.faculty.Email, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.faculty.Email, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.faculty.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.faculty.Password, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.PasswordFor(m => m.faculty.Password, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.faculty.Password, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.faculty.Dept_Id, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(m => m.faculty.Dept_Id, new SelectList(Model.department, "Dept_Id", "Name"), "Select List", new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.faculty.Dept_Id, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" class="btn btn-default" value="Register" />
                    </div>
                </div>
            }
            @using (Html.BeginForm("Logout", "Admins", FormMethod.Get, new { @class = "form-horizontal", role = "form" }))
            {
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Logout" class="btn btn-info" />
                    </div>
                </div>
            }
        </section>
    </div>
</div>

MVCProject/Views/Admins/Create.cshtml
@model MVCProject.Models.Admin

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Admin</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCProject/Views/Admins/Delete.cshtml
@model MVCProject.Models.Admin

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Admin</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVCProject/Views/Admins/Details.cshtml
@model MVCProject.Models.Admin

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Admin</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Admin_Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVCProject/Views/Admins/Edit.cshtml
@model MVCProject.Models.Admin

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Admin</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Admin_Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCProject/Views/Admins/FacultyList.cshtml
@model IEnumerable<MVCProject.Models.Faculty>

@{
    ViewBag.Title = "FacultyList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>FacultyList</h2>
@using (Html.BeginForm("FacultyList", "Admins"))
{
    <div>
        Search By Name:@Html.TextBox("searchstring")
        <input id="Submit1" type="submit" value="Filter" />
    </div>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.dept.Name)
        </th>
        <th>
           @* @Html.DisplayNameFor(model => model.Name) *@
            @Html.ActionLink("Name", "FacultyList",new { sortorder=ViewBag.FacultyName})
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.dept.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Password)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit","faculties","", new { id=item.Fact_Id }) |
            @Html.ActionLink("Details", "Details", "Faculties","",new { id=item.Fact_Id }) |
            @Html.ActionLink("Delete", "Delete", "Faculties","",new { id=item.Fact_Id })
        </td>
    </tr>
}

</table>
@using (Html.BeginForm("Logout", "Admins", FormMethod.Get, new { @class = "form-horizontal", role = "form" }))
{
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Logout" class="btn btn-info" />
        </div>
    </div>
}

MVCProject/Views/Admins/Index.cshtml
@model IEnumerable<MVCProject.Models.Admin>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Password)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Admin_Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Admin_Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Admin_Id })
        </td>
    </tr>
}

</table>

MVCProject/Views/Admins/Registration.cshtml
@model IEnumerable<MVCProject.Models.Faculty>

@{
    ViewBag.Title = "Faculties List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Faculties List</h2>
@using (Html.BeginForm("FacultyList","Admins"))
{
    <div>
        Search By Name:@Html.TextBox("searchstring")
        <input id="Submit1" type="submit" value="Filter"/>
    </div>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.dept.Name)
        </th>
        <th>
            @*  @Html.DisplayNameFor(model => model.Name) *@
            @Html.ActionLink("Name", "FacultyList", new { sortorder = ViewBag.FacultyName })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.dept.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Password)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", "Faculties",new { id=item.Fact_Id }) |
            @Html.ActionLink("Details", "Details", "Faculties",new { id=item.Fact_Id }) |
            @Html.ActionLink("Delete", "Delete", "Faculties",new { id=item.Fact_Id })
        </td>
    </tr>
}

</table>
@using (Html.BeginForm("Logout", "Admins", FormMethod.Get, new { @class = "form-horizontal", role = "form" }))
{
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Logout" class="btn btn-info" />
        </div>
    </div>
}